# Generated by Django 2.1.4 on 2019-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='period',
            field=models.PositiveIntegerField(choices=[(10, '10 days'), (20, '20 days'), (30, '30 days')], default=10),
            preserve_default=False,
        ),
    ]
